const spirits = [

"River Surges in Sunlight",
"Lightning's Swift Strike",
"Vital Strength of the Earth",
"Shadows Flicker Like Flame",
"Thunderspeaker",
"A Spread of Rampant Green",
"Bringer of Dreams and Nightmares",
"Ocean's Hungry Grasp",
"Keeper of the Forbidden Wilds",
"Sharp Fangs Behind the Leaves",
"Heart of the Wildfire",
"Serpent Slumbering Beneath the Island",
"Grinning Trickster Stirs Up Trouble",
"Lure of the Deep Wilderness",
"Many Minds Move as One",
"Shifting Memory of Ages",
"Stone's Unyielding Defiance",
"Volcano Looming High",
"Shroud of Silent Mist",
"Vengeance as a Burning Plague",
"Fractured Days Split the Sky",
"Starlight Seeks Its Form",
"Downpour Drenches the World",
"Finder of Paths Unseen",
"Devouring Teeth Lurk Underfoot",
"Eyes Watch from the Trees",
"Fathomless Mud of the Swamp",
"Rising Heat of Stone and Sand",
"Sun-Bright Whirlwind",
"Ember-Eyed Behemoth",
"Hearth-Vigil",
"Towering Roots of the Jungle",
"Breath of Darkness Down Your Spine",
"Relentless Gaze of the Sun",
"Wandering Voice Keens Delirium",
"Wounded Waters Bleeding",
"Dances Up Earthquakes"

]
